# Generated by Django 3.2 on 2022-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLSAProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200, verbose_name='Event title')),
                ('event_link', models.URLField(verbose_name='Event Link')),
                ('event_description', models.CharField(max_length=400, verbose_name='Event Description')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('event_comments', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Time Posted')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60)),
                ('project_description', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Time Created')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
