# Generated by Django 3.2 on 2022-10-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlsaprogram',
            name='event_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mlsaprogram',
            name='event_link',
            field=models.URLField(blank=True, null=True, verbose_name='Event Link'),
        ),
    ]
